#!/bin/bash

echo `date` ": running on" `hostname`
env | grep OSG
username=`whoami`
#username=osg
export BLASTDB=$OSG_DATA/$username/blastdb
$OSG_APP/$username/ncbi-blast-2.2.28+/bin/blastp -db nr -query $1 -out $2 -num_threads 1
blast_ret=$?
echo `date` ":blast ended at" `date` "ret:$blast_ret"
case $blast_ret in
0)
    echo "success"
    exit 0
    ;;
1)
    echo "Error in query sequence(s) or BLAST options"
    exit 0
    ;;
2)
    echo "Error in blast database"
    exit 1
    ;;
3)
    echo "Error in blast engine"
    exit 1
    ;;
4)
    echo "out of memory"
    exit 1
    ;;
127)
    echo "no blastp"
    exit 1
    ;;
*)
    echo "unknown error"
    exit 1
    ;;
esac

